package ZhuzheeEngine.Scene;

import ZhuzheeEngine.Screen;

import java.awt.*;
import java.util.ArrayList;

public class Scene2D extends Screen {
    protected ArrayList<SceneObject> sceneObjects;
    private Point origin = new Point(0,0);
    /// can access this object by using Scene.Instance (this is called Singleton)
    public static Scene2D Instance;

    public Scene2D() {
        Instance = this;
        sceneObjects = new ArrayList<>();
        setLayout(new BorderLayout());
    }

    public static void register(SceneObject sceneObject) {
        if (Instance == null) {
            throw new IllegalStateException("Scene.register called before any Scene instance was created.");
        }
        Instance.sceneObjects.add(sceneObject);
    }
    public static void remove(SceneObject sceneObject){
        if (Instance == null) {
            throw new IllegalStateException("Scene.remove called before any Scene instance was created.");
        }
        Instance.sceneObjects.remove(sceneObject);
    }
    public static void SetSceneOrigin(Point newPoint){
        if (Instance == null) {
            throw new IllegalStateException("Scene.SetSceneOrigin called before any Scene instance was created.");
        }
        Instance.origin = newPoint;
    }
    /// Getter เพื่อให้ Core.Card สามารถเข้าถึง List ไปเช็ค Slot ได้
    public ArrayList<SceneObject> getGameObjects() {
        return sceneObjects;
    }

    /// sorting rendering squences of gameObjects by z index
    public void sortGameObjects() {
        sceneObjects.sort((o1, o2) -> Float.compare(o1.getZIndex(), o2.getZIndex()));
    }

    /**
     * @Muninthon | Generated by Gemini 8/3/26 - 01:08
     * แปลงพิกัดจากหน้าจอ (Mouse/Screen) -> พิกัดในโลกของเกม (World)
     * เหมาะสำหรับ: เช็คการคลิกเมาส์บน Object ในฉาก
     */
    public static Point Screen2WorldPoint(Point screenPos) {
        if (Instance == null) {
            throw new IllegalStateException("Scene.Screen2WorldPoint called before any Scene instance was created.");
        }

        // คำนวณย้อนกลับจากการ Translate ใน paintComponent
        int centerX = Instance.getWidth() / 2;
        int centerY = Instance.getHeight() / 2;

        int worldX = screenPos.x - (centerX + Instance.origin.x);
        int worldY = screenPos.y - (centerY + Instance.origin.y);

        return new Point(worldX, worldY);
    }

    /**
     * @Muninthon | Generated by Gemini 8/3/26 - 01:08
     * แปลงพิกัดจากโลกของเกม (World) -> พิกัดบนหน้าจอ (Screen/Pixel)
     * เหมาะสำหรับ: วาด UI, หลอดเลือด หรือ Tooltip ให้ตามตัวละคร
     */
    public static Point World2ScreenPoint(Point worldPos) {
        if (Instance == null) {
            throw new IllegalStateException("Scene.World2ScreenPoint called before any Scene instance was created.");
        }

        // คำนวณตาม Logic การ Translate ใน paintComponent
        int centerX = Instance.getWidth() / 2;
        int centerY = Instance.getHeight() / 2;

        int screenX = worldPos.x + centerX + Instance.origin.x;
        int screenY = worldPos.y + centerY + Instance.origin.y;

        return new Point(screenX, screenY);
    }

    @Override
    public Component add(Component comp){
        super.add(comp);

        if(comp instanceof Canvas){
            ((Canvas) comp).isAttachWithPanel = true;
        }
        return comp;
    }
    @Override
    public void remove(Component comp){
        super.remove(comp);
        if(comp instanceof Canvas){
            ((Canvas) comp).isAttachWithPanel = false;
        }
    }
    //--------------------------------------------------------------------
    //------- this is the main update method for scene! (DO NOT CHANGE) ------------
    //--------------------------------------------------------------------

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (!(g instanceof Graphics2D)) {
            return;
        }

        Graphics2D g2d = (Graphics2D) g.create();
        try {
            // set the origin of drawing any objects to center of component
            Point centerPoint = new Point(getWidth() / 2, getHeight() / 2);
            g2d.translate(centerPoint.x + origin.x, centerPoint.y + origin.y);

            sortGameObjects();
            // render object
            for (SceneObject obj : sceneObjects) {
                obj.render(g2d);
            }
        } finally {
            g2d.dispose();
        }
    }
}
